os:
    - linux
    - osx

sudo: required

env:
    global:
        - PACKAGE="sublime_libsass"
        - PCDEPS="true"
    matrix:
        - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/blitzrk/UnitTesting/master/sbin/travis.sh

install:
    - sh travis.sh bootstrap

script:
    - sh travis.sh run_tests

notifications:
    email: false
